# Generated by Django 5.0.6 on 2026-08-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='station',
            field=models.CharField(choices=[('kitchen', 'Кухня'), ('bar', 'Бар')], default='bar', help_text='Куда уходят позиции этой категории: на кухню (еда) или в бар (напитки)', max_length=8, verbose_name='Станция'),
        ),
    ]
