# Generated by Django 5.0.6 on 2026-08-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_station_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/thumbs/', verbose_name='Превью'),
        ),
    ]
