# Generated by Django 5.0.6 on 2026-08-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prep_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время приготовления, мин'),
        ),
    ]
