# Generated by Django 5.0.6 on 2026-08-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productlike_productlike_uniq_like_per_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_stopped',
            field=models.BooleanField(default=False, verbose_name='На стопе (временно)'),
        ),
    ]
