# Generated by Django 5.0.6 on 2026-09-11 08:12

import core.tenancy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_organization_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=core.tenancy.tenant_upload_to('categories'), verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.tenancy.tenant_upload_to('products'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=core.tenancy.tenant_upload_to('products/thumbs'), verbose_name='Превью'),
        ),
    ]
