# Generated by Django 5.0.6 on 2026-09-11 09:51

import core.tenancy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_category_icon_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=core.tenancy.tenant_upload_to('categories'), verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=core.tenancy.tenant_upload_to('products'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, max_length=200, null=True, upload_to=core.tenancy.tenant_upload_to('products/thumbs'), verbose_name='Превью'),
        ),
    ]
