# Generated by Django 5.0.6 on 2026-09-14 19:11

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_variants'),
        ('core', '0026_alter_sitesettings_logo'),
        ('inventory', '0011_recipeitem_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Надбавка, ₽')),
                ('is_stopped', models.BooleanField(default=False, verbose_name='На стопе (временно)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
                'ordering': ['sort_order', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ModifierEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('add', 'Добавить'), ('remove', 'Убрать'), ('swap', 'Заменить')], max_length=8, verbose_name='Действие')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Расход на порцию')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifier_effects', to='inventory.stockitem', verbose_name='Товар склада')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='catalog.modifier', verbose_name='Опция')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
                ('replacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifier_replacements', to='inventory.stockitem', verbose_name='Заменить на')),
            ],
            options={
                'verbose_name': 'Действие опции',
                'verbose_name_plural': 'Действия опций',
                'ordering': ['id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('min_choices', models.PositiveSmallIntegerField(default=0, verbose_name='Минимум выбрать')),
                ('max_choices', models.PositiveSmallIntegerField(default=1, verbose_name='Максимум выбрать')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
                ('products', models.ManyToManyField(blank=True, related_name='modifier_groups', to='catalog.product', verbose_name='Блюда')),
            ],
            options={
                'verbose_name': 'Набор опций',
                'verbose_name_plural': 'Наборы опций',
                'ordering': ['sort_order', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='modifier',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='catalog.modifiergroup', verbose_name='Набор'),
        ),
        migrations.AddConstraint(
            model_name='modifiereffect',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'add'), ('quantity__isnull', False), ('replacement__isnull', True)), models.Q(('kind', 'remove'), ('quantity__isnull', True), ('replacement__isnull', True)), models.Q(('kind', 'swap'), ('quantity__isnull', True), ('replacement__isnull', False)), _connector='OR'), name='modifier_effect_fields_match_kind'),
        ),
    ]
