# Generated by Django 5.0.6 on 2026-09-22 13:15

import core.tenancy
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_modifiers'),
        ('core', '0027_alter_sitesettings_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_is_generated',
            field=models.BooleanField(default=False, verbose_name='Фото сгенерировано'),
        ),
        migrations.CreateModel(
            name='DishwareSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(max_length=200, upload_to=core.tenancy.tenant_upload_to('dishware'), verbose_name='Фото')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Что это')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishware', to='catalog.category', verbose_name='Категория по умолчанию')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Образец посуды',
                'verbose_name_plural': 'Образцы посуды',
                'ordering': ['sort_order', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ImageBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Запущена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_batches', to='catalog.category', verbose_name='Категория')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_batches', to=settings.AUTH_USER_MODEL, verbose_name='Запустил')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Пачка генераций',
                'verbose_name_plural': 'Пачки генераций',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Запрос')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to=core.tenancy.tenant_upload_to('products/ai'), verbose_name='Результат')),
                ('status', models.CharField(choices=[('pending', 'Рисуется'), ('ready', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=8, verbose_name='Статус')),
                ('error', models.CharField(blank=True, max_length=500, verbose_name='Ошибка')),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, help_text='Сколько запрос стоил нам — приходит от OpenRouter', max_digits=8, verbose_name='Стоимость, $')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Поставлено в меню')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='catalog.imagebatch', verbose_name='Пачка')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_generations', to=settings.AUTH_USER_MODEL, verbose_name='Запустил')),
                ('dishware', models.ManyToManyField(blank=True, related_name='generations', to='catalog.dishwaresample', verbose_name='Посуда')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_generations', to='catalog.product', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Генерация фото',
                'verbose_name_plural': 'Генерации фото',
                'ordering': ['-created_at', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ImageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Первое число месяца', verbose_name='Месяц')),
                ('used', models.PositiveIntegerField(default=0, verbose_name='Израсходовано')),
                ('extra', models.PositiveIntegerField(default=0, help_text='Оплаченный пакет сверх тарифа — прибавляется к лимиту месяца', verbose_name='Докуплено')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Лимит генераций фото',
                'verbose_name_plural': 'Лимиты генераций фото',
                'ordering': ['-month'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MenuImageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('studio', 'Студийное фото на светлом фоне'), ('counter', 'На барной стойке'), ('wood', 'На деревянном столе'), ('dark', 'Тёмный фон, контровой свет')], default='studio', max_length=10, verbose_name='Стиль')),
                ('extra_prompt', models.TextField(blank=True, verbose_name='Дописка к запросу')),
                ('aspect_ratio', models.CharField(default='1:1', help_text='1:1 для карточек меню, 4:3 — для широких', max_length=8, verbose_name='Пропорции')),
                ('background', models.ImageField(blank=True, help_text='Своя стойка или стол — попадёт на все фото как фон', max_length=200, null=True, upload_to=core.tenancy.tenant_upload_to('dishware'), verbose_name='Фото фона')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Настройки фото меню',
                'verbose_name_plural': 'Настройки фото меню',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='imagequota',
            constraint=models.UniqueConstraint(fields=('organization', 'month'), name='uniq_image_quota_per_month'),
        ),
    ]
