# Generated by Django 5.0.6 on 2026-09-22 14:56

import core.tenancy
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_dishware_back_in_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegeneration',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refinements', to='catalog.imagegeneration', verbose_name='Правка кадра'),
        ),
        migrations.AddField(
            model_name='menuimagesettings',
            name='sample_photo',
            field=models.ImageField(blank=True, help_text='Одно удачное фото вашего блюда — с него возьмём свет и ракурс', max_length=200, null=True, upload_to=core.tenancy.tenant_upload_to('dishware'), verbose_name='Эталон съёмки'),
        ),
    ]
