# Generated by Django 5.0.6 on 2026-09-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_imagegeneration_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='picks',
            field=models.PositiveIntegerField(default=0, verbose_name='Выбирали за месяц'),
        ),
    ]
