# Generated by Django 5.0.6 on 2026-09-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_modifier_picks'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='upsell_bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Надбавка исполнителю заказа за каждую такую опцию. 0 — не допродажа.', max_digits=10, verbose_name='За допродажу, ₽'),
        ),
    ]
