# Generated by Django 5.0.6 on 2026-08-01 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remap_order_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cashier',
        ),
        migrations.AddField(
            model_name='order',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл счёт'),
        ),
        migrations.AddField(
            model_name='order',
            name='drinks_ready',
            field=models.BooleanField(default=False, verbose_name='Напитки готовы'),
        ),
        migrations.AddField(
            model_name='order',
            name='food_ready',
            field=models.BooleanField(default=False, verbose_name='Еда готова'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('paid', 'Закрыт'), ('cancelled', 'Отменён')], default='open', max_length=16, verbose_name='Статус'),
        ),
    ]
