# Generated by Django 5.0.6 on 2026-08-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_drop_order_station_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='guest',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Гость'),
        ),
    ]
