# Generated by Django 5.0.6 on 2026-08-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_seed_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='public_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Токен отслеживания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Ждёт официанта'), ('open', 'Открыт'), ('paid', 'Закрыт'), ('cancelled', 'Отменён')], default='open', max_length=16, verbose_name='Статус'),
        ),
    ]
