# Generated by Django 5.0.6 on 2026-08-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_client_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, help_text='Пожелания к заказу: «без лука», «аллергия», «стол у окна» и т.п.', max_length=300, verbose_name='Комментарий официанта'),
        ),
    ]
