# Generated by Django 5.0.6 on 2026-08-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_seed_tables_11_15'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drinks_served_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Напитки поданы'),
        ),
        migrations.AddField(
            model_name='order',
            name='food_served_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Еда подана'),
        ),
    ]
