# Generated by Django 5.0.6 on 2026-08-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_drinks_served_at_order_food_served_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_written_off_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Склад списан'),
        ),
    ]
