# Generated by Django 5.0.6 on 2026-08-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderitem_stock_written_off_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fiscal_receipt',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Фискальный чек'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Ждёт официанта'), ('open', 'Открыт'), ('awaiting', 'К оплате'), ('paid', 'Закрыт'), ('cancelled', 'Отменён')], default='open', max_length=16, verbose_name='Статус'),
        ),
    ]
