# Generated by Django 5.0.6 on 2026-08-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_fiscal_receipt_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id'], 'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'},
        ),
    ]
