# Generated by Django 5.0.6 on 2026-09-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='daily_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер за день'),
        ),
    ]
