# Generated by Django 5.0.6 on 2026-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_service_mode_and_daily_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Списано бонусами'),
        ),
    ]
