# Generated by Django 5.0.6 on 2026-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_organization_client_organization_last_seen_at_and_more'),
        ('orders', '0024_organization_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название / номер'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_table_per_org'),
        ),
    ]
