# Generated by Django 5.0.6 on 2026-09-14 19:12

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_modifiers'),
        ('core', '0026_alter_sitesettings_logo'),
        ('orders', '0026_orderitem_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price_delta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Надбавка, ₽')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.modifier', verbose_name='Опция')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.orderitem', verbose_name='Позиция')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Опция позиции',
                'verbose_name_plural': 'Опции позиций',
                'ordering': ['id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='orderitemmodifier',
            constraint=models.UniqueConstraint(fields=('order_item', 'modifier'), name='uniq_modifier_per_order_item'),
        ),
    ]
