# Generated by Django 5.0.6 on 2026-09-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_item_modifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оплачен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Ждёт официанта'), ('unpaid', 'Ждёт оплаты'), ('open', 'Открыт'), ('awaiting', 'К оплате'), ('paid', 'Закрыт'), ('cancelled', 'Отменён')], default='open', max_length=16, verbose_name='Статус'),
        ),
    ]
