# Generated by Django 5.0.6 on 2026-09-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_order_performer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Деньги возвращены'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Ждёт официанта'), ('unpaid', 'Ждёт оплаты'), ('open', 'Открыт'), ('awaiting', 'К оплате'), ('paid', 'Закрыт'), ('refunded', 'Возврат'), ('cancelled', 'Отменён')], default='open', max_length=16, verbose_name='Статус'),
        ),
    ]
