# Generated by Django 5.0.6 on 2026-09-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_order_refunded_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodifier',
            name='upsell_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='За допродажу, ₽'),
        ),
    ]
