# Generated by Django 5.0.6 on 2026-10-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_upsell_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_contact',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Контакт для чека'),
        ),
    ]
