# Generated by Django 5.0.6 on 2026-09-11 08:36

import billing.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_organization_domain_organization_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('contact_person', models.CharField(blank=True, max_length=160, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Появился')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('start', 'Старт'), ('hall', 'Зал'), ('max', 'Максимум')], default='start', max_length=8, verbose_name='Тариф')),
                ('paid_until', models.DateField(default=billing.models.trial_end, help_text='Новая точка получает неделю бесплатно', verbose_name='Оплачено до')),
                ('grace_days', models.PositiveSmallIntegerField(default=7, help_text='Сколько дней после «оплачено до» точка ещё работает', verbose_name='Грейс, дней')),
                ('is_internal', models.BooleanField(default=False, help_text='Наше заведение: не биллится и никогда не блокируется', verbose_name='Своя точка')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.organization', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма, ₽')),
                ('months', models.PositiveSmallIntegerField(default=1, verbose_name='Месяцев')),
                ('paid_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата оплаты')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-paid_at', '-id'],
            },
        ),
    ]
