# Generated by Django 5.0.6 on 2026-09-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='image_limit',
            field=models.PositiveIntegerField(default=100, help_text='Сколько картинок точка может нарисовать за месяц. Разовую добавку удобнее давать в «Лимитах генераций фото».', verbose_name='Генераций в месяц'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='images_enabled',
            field=models.BooleanField(default=True, help_text='Выключить — раздел пропадёт у кафе из каталога', verbose_name='Генерация фото меню'),
        ),
    ]
