# Generated by Django 5.0.6 on 2026-10-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_organization_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltymember',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Согласие на обработку данных'),
        ),
        migrations.AddField(
            model_name='loyaltymember',
            name='source',
            field=models.CharField(choices=[('guest', 'Сам гость'), ('staff', 'Персонал'), ('import', 'Перенос из прежней системы')], default='guest', max_length=10, verbose_name='Как попал в программу'),
        ),
        migrations.AlterField(
            model_name='bonustransaction',
            name='type',
            field=models.CharField(choices=[('welcome', 'Приветственные'), ('earn', 'Начисление за заказ'), ('redeem', 'Списание за заказ'), ('return', 'Возврат списанных'), ('adjust', 'Ручная корректировка'), ('import', 'Перенос из прежней системы')], max_length=12, verbose_name='Тип'),
        ),
    ]
