# Generated by Django 5.0.6 on 2026-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_organization_client_organization_last_seen_at_and_more'),
        ('finance', '0005_organization_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_expense_category_per_org'),
        ),
    ]
