# Generated by Django 5.0.6 on 2026-08-03 13:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория склада',
                'verbose_name_plural': 'Категории склада',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Поставщик')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Оприходовал')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('unit', models.CharField(choices=[('g', 'г'), ('ml', 'мл'), ('pcs', 'шт')], default='pcs', max_length=4, verbose_name='Единица')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Остаток')),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Если остаток опустится до этого значения — позиция подсветится', max_digits=12, null=True, verbose_name='Порог «заканчивается»')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.stockcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Складская позиция',
                'verbose_name_plural': 'Складские позиции',
                'ordering': ['category__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за единицу, ₽')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.receipt', verbose_name='Приход')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='inventory.stockitem', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Позиция прихода',
                'verbose_name_plural': 'Позиции прихода',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Изменение')),
                ('kind', models.CharField(choices=[('receipt', 'Приход'), ('adjust', 'Корректировка')], max_length=12, verbose_name='Тип')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem', verbose_name='Позиция')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.receipt', verbose_name='Приход')),
            ],
            options={
                'verbose_name': 'Движение остатка',
                'verbose_name_plural': 'Движения остатка',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_stockitem_per_category'),
        ),
    ]
