# Generated by Django 5.0.6 on 2026-08-06 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipt_scans/%Y/%m/', verbose_name='Фото чека')),
                ('status', models.CharField(choices=[('pending', 'Распознаётся'), ('parsed', 'Распознан'), ('failed', 'Ошибка'), ('confirmed', 'Оприходован')], default='pending', max_length=12, verbose_name='Статус')),
                ('parsed', models.JSONField(blank=True, null=True, verbose_name='Распознанное')),
                ('error', models.CharField(blank=True, max_length=500, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_scans', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan', to='inventory.receipt', verbose_name='Приход')),
            ],
            options={
                'verbose_name': 'Скан чека',
                'verbose_name_plural': 'Сканы чеков',
                'ordering': ['-created_at'],
            },
        ),
    ]
