# Generated by Django 5.0.6 on 2026-08-13 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_is_stopped'),
        ('inventory', '0004_merge_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('is_auto', models.BooleanField(default=True, help_text='Строку предложила программа; ручные строки не пересчитываются', verbose_name='Добавлено автоматически')),
                ('is_done', models.BooleanField(default=False, verbose_name='Куплено')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Строка закупа',
                'verbose_name_plural': 'Строки закупа',
                'ordering': ['item__category__sort_order', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Закуп',
                'verbose_name_plural': 'Закуп',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Расход на порцию')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Строка тех карты',
                'verbose_name_plural': 'Тех карты блюд',
                'ordering': ['product__name', 'item__name'],
            },
        ),
        # Ограничение снимаем ДО удаления поля product: вместе с колонкой Postgres
        # снесёт и её индекс, и RemoveConstraint потом не найдёт, что удалять.
        migrations.RemoveConstraint(
            model_name='stockitem',
            name='uniq_stockitem_per_product',
        ),
        migrations.RemoveField(
            model_name='stockproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['category__sort_order', 'name'], 'verbose_name': 'Товар склада', 'verbose_name_plural': 'Товары склада'},
        ),
        migrations.AlterModelOptions(
            name='stockitemalias',
            options={'ordering': ['name'], 'verbose_name': 'Вариант / название в чеке', 'verbose_name_plural': 'Варианты и названия в чеках'},
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stockitemalias',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.stockitem', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Приход'), ('adjust', 'Корректировка'), ('sale', 'Списание по тех карте'), ('return', 'Возврат отменённого')], max_length=12, verbose_name='Тип'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_stockitem_per_category'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='inventory.stockitem', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaselist', verbose_name='Закуп'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='inventory.stockitem', verbose_name='Товар склада'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='catalog.product', verbose_name='Блюдо'),
        ),
        migrations.DeleteModel(
            name='StockProduct',
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.UniqueConstraint(fields=('purchase', 'item'), name='uniq_purchaseline_per_list'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.UniqueConstraint(fields=('product', 'item'), name='uniq_recipeitem_per_product'),
        ),
    ]
