# Generated by Django 5.0.6 on 2026-09-11 08:12

import core.tenancy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_organization_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptscan',
            name='image',
            field=models.ImageField(upload_to=core.tenancy.tenant_upload_to('receipt_scans'), verbose_name='Фото чека'),
        ),
    ]
