# Generated by Django 5.0.6 on 2026-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_organization_client_organization_last_seen_at_and_more'),
        ('inventory', '0008_alter_receiptscan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselist',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='stockcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stockitemalias',
            name='norm',
            field=models.CharField(max_length=200, verbose_name='Нормализованное'),
        ),
        migrations.AddConstraint(
            model_name='purchaselist',
            constraint=models.UniqueConstraint(fields=('organization', 'date'), name='uniq_purchase_list_per_org'),
        ),
        migrations.AddConstraint(
            model_name='stockcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_stock_category_per_org'),
        ),
        migrations.AddConstraint(
            model_name='stockitemalias',
            constraint=models.UniqueConstraint(fields=('organization', 'norm'), name='uniq_alias_per_org'),
        ),
    ]
