# Generated by Django 5.0.6 on 2026-09-11 09:51

import core.tenancy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_purchaselist_date_alter_stockcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptscan',
            name='image',
            field=models.ImageField(max_length=200, upload_to=core.tenancy.tenant_upload_to('receipt_scans'), verbose_name='Фото чека'),
        ),
    ]
