# Generated by Django 5.0.6 on 2026-09-15 08:16

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_sitesettings_plan_and_more'),
        ('inventory', '0011_recipeitem_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Первое число месяца', verbose_name='Месяц')),
                ('used', models.PositiveIntegerField(default=0, verbose_name='Израсходовано')),
                ('extra', models.PositiveIntegerField(default=0, help_text='Оплаченный пакет сверх тарифа — прибавляется к лимиту месяца', verbose_name='Докуплено')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Лимит распознаваний',
                'verbose_name_plural': 'Лимиты распознаваний',
                'ordering': ['-month'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='scanquota',
            constraint=models.UniqueConstraint(fields=('organization', 'month'), name='uniq_scan_quota_per_month'),
        ),
    ]
