# Generated by Django 5.0.6 on 2026-09-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_scanquota_scanquota_uniq_scan_quota_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Цена за единицу, ₽'),
        ),
    ]
