# Generated by Django 5.0.6 on 2026-06-24 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('order', 'Оплата заказа'), ('topup', 'Пополнение токенов')], max_length=16, verbose_name='Назначение')),
                ('status', models.CharField(choices=[('pending', 'Создан'), ('succeeded', 'Оплачен'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма, ₽')),
                ('provider', models.CharField(default='yookassa', max_length=32, verbose_name='Провайдер')),
                ('external_id', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='ID у провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
