# Generated by Django 5.0.6 on 2026-08-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fiscal_receipt',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Фискальный чек'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта'), ('qr', 'QR / СБП')], default='', max_length=8, verbose_name='Способ'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Создан'), ('succeeded', 'Оплачен'), ('failed', 'Ошибка'), ('cancelled', 'Отменён')], default='pending', max_length=16, verbose_name='Статус'),
        ),
    ]
