# Generated by Django 5.0.6 on 2026-09-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_fiscal_receipt_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='manual', max_length=32, verbose_name='Провайдер'),
        ),
    ]
