# Generated by Django 5.0.6 on 2026-09-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_sitesettings_logo'),
        ('orders', '0025_alter_table_name_table_uniq_table_per_org'),
        ('payments', '0006_organization_required'),
        ('wallet', '0003_organization_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ID у провайдера'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', None), _negated=True), fields=('organization', 'external_id'), name='uniq_payment_external_id_per_org'),
        ),
    ]
