# Generated by Django 5.0.6 on 2026-09-22 12:06

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_sitesettings_plan_and_more'),
        ('payments', '0007_external_id_per_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquiringCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32, verbose_name='Банк')),
                ('payload', models.TextField(blank=True, default='', verbose_name='Доступы (шифр)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлены')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Доступы к банку',
                'verbose_name_plural': 'Доступы к банкам',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='acquiringcredentials',
            constraint=models.UniqueConstraint(fields=('organization', 'provider'), name='uniq_acquiring_credentials_per_org'),
        ),
    ]
