# Generated by Django 5.0.6 on 2026-09-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_acquiringcredentials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('order', 'Оплата заказа'), ('topup', 'Пополнение токенов'), ('refund', 'Возврат гостю')], max_length=16, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Создан'), ('succeeded', 'Оплачен'), ('failed', 'Ошибка'), ('cancelled', 'Отменён'), ('refunded', 'Возвращён')], default='pending', max_length=16, verbose_name='Статус'),
        ),
    ]
