# Generated by Django 5.0.6 on 2026-10-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_confirmed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='kassa_receipt_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Чек на кассе (id)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='kassa_rrn',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='RRN операции'),
        ),
        migrations.AddField(
            model_name='payment',
            name='kassa_slip_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Слип оплаты картой (id)'),
        ),
    ]
