# Generated by Django 5.0.6 on 2026-10-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_payment_kassa_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='kassa_meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ход операции на кассе'),
        ),
    ]
