# Generated by Django 5.0.6 on 2026-10-02 06:49

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_bonus_redeem_staff'),
        ('payments', '0012_payment_kassa_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='KassaSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32, verbose_name='Касса')),
                ('session', models.TextField(blank=True, default='', verbose_name='Сессия кабинета (шифр)')),
                ('session_until', models.DateTimeField(blank=True, null=True, verbose_name='Сессия до')),
                ('attempted_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя удачная')),
                ('error', models.CharField(blank=True, default='', max_length=300, verbose_name='Ошибка последней попытки')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Синхронизация кассы',
                'verbose_name_plural': 'Синхронизация касс',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='kassasync',
            constraint=models.UniqueConstraint(fields=('organization', 'provider'), name='uniq_kassa_sync_per_org'),
        ),
    ]
