# Generated by Django 5.0.6 on 2026-10-02 15:42

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_bonus_redeem_staff'),
        ('payments', '0013_kassa_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32, verbose_name='Банк или касса')),
                ('error', models.CharField(blank=True, default='', max_length=300, verbose_name='Последняя ошибка')),
                ('error_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда')),
                ('error_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Заказ')),
                ('ok_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний удачный переход к оплате')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Состояние приёма оплаты',
                'verbose_name_plural': 'Состояние приёма оплаты',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='paymenthealth',
            constraint=models.UniqueConstraint(fields=('organization', 'provider'), name='uniq_payment_health_per_org'),
        ),
    ]
