# Generated by Django 5.0.6 on 2026-08-14 13:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0018_orderitem_stock_written_off_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Оплата за смену')),
                ('bonus_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Бонус, % от выручки')),
                ('penalty_table', models.CharField(blank=True, help_text='Название стола на момент открытия смены.', max_length=32, verbose_name='Штрафной стол')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ShiftMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('client', 'Клиент'), ('waiter', 'Официант'), ('cook', 'Повар'), ('bar', 'Бар'), ('warehouse', 'Склад'), ('admin', 'Админ')], help_text='Роль на момент постановки в смену — роль в профиле может поменяться.', max_length=16, verbose_name='Роль в смене')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Поставлен')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Поставил в смену')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='shifts.shift', verbose_name='Смена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_members', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Работник в смене',
                'verbose_name_plural': 'Работники в смене',
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=Decimal('2000'), help_text='Сколько получает каждый работник за отработанный день.', max_digits=10, verbose_name='Оплата за смену')),
                ('bonus_percent', models.DecimalField(decimal_places=2, default=Decimal('9'), help_text='Процент от выручки дня. Делится поровну на всех в смене.', max_digits=5, verbose_name='Бонус, % от выручки')),
                ('penalty_table', models.ForeignKey(blank=True, help_text='Стол, на который официант оформляет подарки гостям за косяки персонала. Сумма его заказов за день делится на всех в смене и вычитается из оплаты. В выручку дня эти заказы не идут.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.table', verbose_name='Штрафной стол')),
            ],
            options={
                'verbose_name': 'Настройки смен и оплаты',
                'verbose_name_plural': 'Настройки смен и оплаты',
            },
        ),
        migrations.AddConstraint(
            model_name='shiftmember',
            constraint=models.UniqueConstraint(fields=('shift', 'user'), name='unique_shift_member'),
        ),
    ]
