# Generated by Django 5.0.6 on 2026-08-25 09:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='manual_penalty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Ручное списание с персонала за косяки — делится поровну на всех в смене и вычитается из выплаты, помимо штрафного стола.', max_digits=10, verbose_name='Доп. штраф за смену'),
        ),
    ]
