# Generated by Django 5.0.6 on 2026-09-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_organization_domain_organization_is_active_and_more'),
        ('orders', '0024_organization_required'),
        ('shifts', '0004_organization_required'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shiftsettings',
            constraint=models.UniqueConstraint(fields=('organization',), name='unique_shiftsettings_per_org'),
        ),
    ]
