# Generated by Django 5.0.6 on 2026-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_organization_client_organization_last_seen_at_and_more'),
        ('shifts', '0005_shiftsettings_unique_shiftsettings_per_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('organization', 'date'), name='uniq_shift_per_org'),
        ),
    ]
