# Generated by Django 5.0.6 on 2026-09-30 08:11

import django.db.models.deletion
import django.db.models.manager
import shifts.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_sitesettings_kassa'),
        ('shifts', '0006_alter_shift_date_shift_uniq_shift_per_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='scheme',
            field=models.CharField(choices=[('even', 'Ставка + % от выручки поровну'), ('result', 'Ставка + бонусы за результат')], default='even', max_length=8, verbose_name='Схема оплаты'),
        ),
        migrations.AddField(
            model_name='shift',
            name='senior_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Надбавка старшему'),
        ),
        migrations.AddField(
            model_name='shiftmember',
            name='ends_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Ушёл'),
        ),
        migrations.AddField(
            model_name='shiftmember',
            name='in_kpi',
            field=models.BooleanField(default=False, verbose_name='Участвует в КПД'),
        ),
        migrations.AddField(
            model_name='shiftmember',
            name='is_senior',
            field=models.BooleanField(default=False, verbose_name='Старший смены'),
        ),
        migrations.AddField(
            model_name='shiftmember',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ставка по типу смены и роли. Пусто — общая ставка смены.', max_digits=10, null=True, verbose_name='Ставка'),
        ),
        migrations.AddField(
            model_name='shiftmember',
            name='shift_type_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Название типа'),
        ),
        migrations.AddField(
            model_name='shiftmember',
            name='starts_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Пришёл'),
        ),
        migrations.AddField(
            model_name='shiftsettings',
            name='kpi_roles',
            field=models.JSONField(blank=True, default=shifts.models.default_kpi_roles, help_text='Кто делит выручку и получает бонус за КПД. Остальные — только ставку.', verbose_name='Роли в бонусе за КПД'),
        ),
        migrations.AddField(
            model_name='shiftsettings',
            name='scheme',
            field=models.CharField(choices=[('even', 'Ставка + % от выручки поровну'), ('result', 'Ставка + бонусы за результат')], default='even', max_length=8, verbose_name='Схема оплаты'),
        ),
        migrations.AddField(
            model_name='shiftsettings',
            name='senior_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Сверх ставки тому, кто отмечен старшим смены. Только в оплате за результат.', max_digits=10, verbose_name='Надбавка старшему'),
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('starts_at', models.TimeField(verbose_name='Начало')),
                ('ends_at', models.TimeField(help_text='Если раньше начала — смена заканчивается на следующий день.', verbose_name='Конец')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Тип смены',
                'verbose_name_plural': 'Типы смен',
                'ordering': ['sort_order', 'starts_at', 'id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ShiftRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('waiter', 'Официант'), ('cook', 'Повар'), ('bar', 'Бар'), ('warehouse', 'Склад'), ('admin', 'Админ')], max_length=16, verbose_name='Роль')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ставка')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shifts.shifttype', verbose_name='Тип смены')),
            ],
            options={
                'verbose_name': 'Ставка за смену',
                'verbose_name_plural': 'Ставки за смену',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='shiftmember',
            name='shift_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='shifts.shifttype', verbose_name='Тип смены'),
        ),
        migrations.AddConstraint(
            model_name='shiftrate',
            constraint=models.UniqueConstraint(fields=('shift_type', 'role'), name='uniq_rate_per_type_role'),
        ),
    ]
