# Generated by Django 5.0.6 on 2026-09-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_shift_types_and_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='kpi_grid',
            field=models.JSONField(blank=True, default=list, verbose_name='Сетка бонуса за КПД'),
        ),
        migrations.AddField(
            model_name='shiftsettings',
            name='kpi_grid',
            field=models.JSONField(blank=True, default=list, help_text='Ступени [{"from": "2500", "bonus": "500"}, …]: от скольких ₽ личной выручки в час (включительно) — какая надбавка за смену.', verbose_name='Сетка бонуса за КПД'),
        ),
    ]
