# Generated by Django 5.0.6 on 2026-09-30 08:53

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_modifier_picks'),
        ('core', '0030_sitesettings_kassa'),
        ('shifts', '0008_kpi_grid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Надбавка за штуку')),
                ('starts_at', models.DateTimeField(verbose_name='Действует с')),
                ('ends_at', models.DateTimeField(help_text='Не включительно.', verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Завёл')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization', verbose_name='Заведение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='focus_items', to='catalog.product', verbose_name='Товар')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='focus_items', to='catalog.productvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Фокусная позиция',
                'verbose_name_plural': 'Фокусные позиции',
                'ordering': ['starts_at', 'id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
