# Generated by Django 5.0.6 on 2026-10-01 08:28

from decimal import Decimal
from django.db import migrations, models


def fill_planned_hours(apps, schema_editor):
    """Плановые часы у уже поставленных в смену — из их типа смены."""
    from decimal import Decimal

    ShiftMember = apps.get_model("shifts", "ShiftMember")
    for m in ShiftMember.objects.filter(shift_type__isnull=False).select_related("shift_type"):
        t = m.shift_type
        minutes = (t.ends_at.hour * 60 + t.ends_at.minute) - (t.starts_at.hour * 60 + t.starts_at.minute)
        if minutes <= 0:
            minutes += 24 * 60
        m.planned_hours = (Decimal(minutes) / 60).quantize(Decimal("0.01"))
        m.save(update_fields=["planned_hours"])


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_focus_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='prorate',
            field=models.BooleanField(default=False, verbose_name='Ставка по отработанным часам'),
        ),
        migrations.AddField(
            model_name='shiftmember',
            name='planned_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Часов по плану'),
        ),
        migrations.AddField(
            model_name='shiftsettings',
            name='prorate',
            field=models.BooleanField(default=False, help_text='Ставка смены ÷ плановые часы × отработанные часы (до ближайшего часа). Выключено — ставка за смену целиком.', verbose_name='Ставка по отработанным часам'),
        ),
        migrations.AlterField(
            model_name='shiftsettings',
            name='senior_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Сверх ставки тому, кто отмечен старшим смены. Только в оплате за результат. При оплате по часам — ₽ в час, иначе — ₽ за смену.', max_digits=10, verbose_name='Надбавка старшему'),
        ),
        migrations.RunPython(fill_planned_hours, migrations.RunPython.noop),
    ]
