# Generated by Django 5.0.6 on 2026-08-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('waiter', 'Официант'), ('cook', 'Повар'), ('bar', 'Бар'), ('admin', 'Админ')], default='client', max_length=16, verbose_name='Роль'),
        ),
    ]
