# Generated by Django 5.0.6 on 2026-08-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cashier_to_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('waiter', 'Официант'), ('cook', 'Повар'), ('bar', 'Бар'), ('warehouse', 'Склад'), ('admin', 'Админ')], default='client', max_length=16, verbose_name='Роль'),
        ),
    ]
