# Generated by Django 5.0.6 on 2026-06-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Кафе', max_length=120, verbose_name='Название')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Слоган')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Логотип')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('working_hours', models.CharField(blank=True, max_length=120, verbose_name='Часы работы')),
                ('instagram', models.CharField(blank=True, max_length=200, verbose_name='Instagram')),
                ('telegram', models.CharField(blank=True, max_length=200, verbose_name='Telegram')),
                ('about', models.TextField(blank=True, verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
