# Generated by Django 5.0.6 on 2026-08-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='HEX вида #1f58a6; пусто — фирменный цвет темы', max_length=7, verbose_name='Акцентный цвет'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('neutral', 'Нейтраль'), ('warm', 'Тёплая'), ('strict', 'Строгая'), ('humu', 'хуму')], default='neutral', max_length=20, verbose_name='Тема оформления'),
        ),
    ]
