# Generated by Django 5.0.6 on 2026-08-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_existing_install_keeps_humu_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='acquirer',
            field=models.CharField(blank=True, help_text='Кто принимает онлайн-оплату, напр. «АО «ТБанк» (Т-Касса)»', max_length=160, verbose_name='Эквайер'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_updated',
            field=models.CharField(blank=True, help_text='Как показывать на юр. страницах, напр. «3 августа 2026 г.»', max_length=60, verbose_name='Дата редакции документов'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='merchant_account',
            field=models.CharField(blank=True, max_length=34, verbose_name='Расчётный счёт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='merchant_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='merchant_bank',
            field=models.CharField(blank=True, max_length=160, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='merchant_bank_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес банка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='merchant_bank_inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН банка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='merchant_bik',
            field=models.CharField(blank=True, max_length=12, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='merchant_corr_account',
            field=models.CharField(blank=True, max_length=34, verbose_name='Корр. счёт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='merchant_inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное наименование'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='merchant_ogrn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ОГРН / ОГРНИП'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='merchant_short',
            field=models.CharField(blank=True, max_length=120, verbose_name='Краткое наименование'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='merchant_type',
            field=models.CharField(blank=True, help_text='Напр. «Индивидуальный предприниматель» или «ООО»', max_length=120, verbose_name='Форма'),
        ),
    ]
