# Generated by Django 5.0.6 on 2026-08-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_existing_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('neutral', 'Нейтраль'), ('warm', 'Тёплая'), ('strict', 'Строгая'), ('island', 'Островная')], default='neutral', max_length=20, verbose_name='Тема оформления'),
        ),
    ]
