# Generated by Django 5.0.6 on 2026-08-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_move_humu_theme_to_island'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='app_short_name',
            field=models.CharField(blank=True, help_text='Подпись под иконкой на телефоне. Пусто — обрежется из названия', max_length=12, verbose_name='Короткое имя приложения'),
        ),
    ]
