# Generated by Django 5.0.6 on 2026-09-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_app_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dark_by_default',
            field=models.BooleanField(default=False, help_text='Какой режим видит гость, пока сам не переключил', verbose_name='Тёмная тема по умолчанию'),
        ),
    ]
