# Generated by Django 5.0.6 on 2026-09-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dark_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='service_mode',
            field=models.CharField(choices=[('hall', 'Зал с официантами'), ('counter', 'Стойка / окно выдачи')], default='hall', help_text='«Стойка» — для точек без зала: гость заказывает по QR, забирает по номеру. Столов и официанта нет, заказ сразу уходит в работу.', max_length=16, verbose_name='Формат обслуживания'),
        ),
    ]
