# Generated by Django 5.0.6 on 2026-09-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_service_mode_and_daily_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('neutral', 'Нейтраль'), ('warm', 'Тёплая'), ('strict', 'Строгая'), ('island', 'Островная'), ('padacha', 'Падача')], default='neutral', max_length=20, verbose_name='Тема оформления'),
        ),
    ]
