# Generated by Django 5.0.6 on 2026-09-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_padacha_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='item_remove_code',
            field=models.CharField(blank=True, help_text='Официант должен назвать этот код, чтобы убрать позицию, которую кухня/бар уже готовят. Новые позиции убираются без кода. Пусто — убрать позицию в работе не может никто (кроме админа).', max_length=20, verbose_name='Код на удаление позиций в работе'),
        ),
    ]
