# Generated by Django 5.0.6 on 2026-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_item_remove_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='acquiring',
            field=models.CharField(choices=[('none', 'Нет онлайн-оплаты'), ('tbank', 'Т-Банк (Т-Касса)'), ('sber', 'Сбербанк (в т.ч. через Эвотор)')], default='none', help_text='Кто принимает оплату картой онлайн. Доступы задаются переменными окружения на сервере заведения, не здесь.', max_length=16, verbose_name='Интернет-эквайринг'),
        ),
    ]
