# Generated by Django 5.0.6 on 2026-09-09 08:47

from django.db import migrations, models


def grandfather_existing(apps, schema_editor):
    """Установкам, которые уже работают, оставить весь функционал.

    Тарифы появились позже продукта: кафе-флагман, точка в парке и
    демо-стенд пользуются складом и финансами — отбирать их миграцией
    нельзя. Новая установка записи ещё не имеет и получит дефолт start.
    """
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.filter(pk=1).update(plan="max")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_acquiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='plan',
            field=models.CharField(choices=[('start', 'Старт'), ('hall', 'Зал'), ('max', 'Максимум')], default='start', help_text='«Старт» — меню, заказы и оплаты; «Зал» — плюс экраны кухни и бара; «Максимум» — плюс склад, смены и финансы.', max_length=8, verbose_name='Тариф'),
        ),
        migrations.RunPython(grandfather_existing, migrations.RunPython.noop),
    ]
