# Generated by Django 5.0.6 on 2026-09-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, max_length=8, verbose_name='Тариф из лицензии')),
                ('paid_until', models.DateField(blank=True, null=True, verbose_name='Оплачено до')),
                ('grace_days', models.PositiveSmallIntegerField(default=7, verbose_name='Грейс, дней')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Ответ выдан')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя сверка')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензия',
            },
        ),
    ]
