# Generated by Django 5.0.6 on 2026-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_sitesettings_acquiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bonus_earn_percent',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Процент от оплаченной деньгами суммы чека', max_digits=5, verbose_name='Начисление с покупки, %'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bonus_enabled',
            field=models.BooleanField(default=False, help_text='Начисление и списание бонусов. 1 бонус = 1 ₽', verbose_name='Бонусная программа включена'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bonus_redeem_guest',
            field=models.BooleanField(default=False, help_text='Гость применяет бонусы к своему заказу в приложении', verbose_name='Гость списывает сам'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bonus_redeem_waiter',
            field=models.BooleanField(default=True, help_text='На закрытии счёта официант находит гостя по телефону и списывает', verbose_name='Официант списывает бонусы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bonus_welcome',
            field=models.PositiveIntegerField(default=200, help_text='Начисляются один раз при регистрации в программе', verbose_name='Приветственные бонусы'),
        ),
    ]
