# Generated by Django 5.0.6 on 2026-09-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sitesettings_bonus_earn_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='online_payment_on',
            field=models.BooleanField(default=True, help_text='Быстрый выключатель для гостевой кнопки «Оплатить картой». Работает, только если банк подключён и заданы его доступы.', verbose_name='Принимать оплату картой онлайн'),
        ),
    ]
