# Generated by Django 5.0.6 on 2026-09-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sitesettings_online_payment_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensestate',
            name='internal',
            field=models.BooleanField(default=False, verbose_name='Своя точка'),
        ),
    ]
