# Generated by Django 5.0.6 on 2026-09-11 08:12

import core.tenancy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_organization_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Напр. moyokafe.padacha.ru — по нему гость попадает именно сюда', max_length=200, verbose_name='Домен'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Выключенное заведение не отвечает по своему домену', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='organization',
            name='license_key',
            field=models.CharField(blank=True, default='', help_text='Из пульта «Падачи». Пусто — заведение не биллится', max_length=64, verbose_name='Ключ лицензии'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.tenancy.tenant_upload_to('site'), verbose_name='Логотип'),
        ),
        migrations.AddConstraint(
            model_name='licensestate',
            constraint=models.UniqueConstraint(fields=('organization',), name='unique_licensestate_per_org'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('domain', ''), _negated=True), fields=('domain',), name='unique_organization_domain'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.UniqueConstraint(fields=('organization',), name='unique_sitesettings_per_org'),
        ),
    ]
