# Generated by Django 5.0.6 on 2026-09-11 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0024_organization_domain_organization_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Заказчик. У сети точек он один на все', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='billing.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выходила на связь'),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_version',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='license_key',
            field=models.CharField(blank=True, default='', help_text='Нужен только внешней установке — она спрашивает подписку по нему через /api/license/. Заведению этой установки не нужен', max_length=64, verbose_name='Ключ лицензии'),
        ),
    ]
