# Generated by Django 5.0.6 on 2026-09-11 09:51

import core.tenancy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_organization_client_organization_last_seen_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=core.tenancy.tenant_upload_to('site'), verbose_name='Логотип'),
        ),
    ]
