# Generated by Django 5.0.6 on 2026-09-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_sitesettings_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='prepay_required',
            field=models.BooleanField(default=True, help_text='Формат «Стойка»: заказ гостя ждёт оплаты и не уходит на кухню, пока не оплачен. Работает, только если включена оплата картой — иначе гостю нечем платить, и заказ принимается как раньше.', verbose_name='Готовить только после оплаты'),
        ),
    ]
