# Generated by Django 5.0.6 on 2026-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_sitesettings_prepay_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ordering_pause_note',
            field=models.CharField(blank=True, help_text='Напр. «Кофемашина на профилактике, ждём к 14:00». Пусто — гость увидит просто «Технический перерыв»', max_length=200, verbose_name='Что показать гостю'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ordering_paused',
            field=models.BooleanField(default=False, help_text='Гость видит меню, но отправить заказ не может', verbose_name='Технический перерыв'),
        ),
    ]
