# Generated by Django 5.0.6 on 2026-09-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_sitesettings_ordering_pause_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='kassa',
            field=models.CharField(choices=[('none', 'Нет — оплату отмечает сотрудник'), ('aqsi', 'aQsi (смарт-касса Т-Банка)')], default='none', help_text='Куда уходит заказ, когда гость выбирает «Оплатить на кассе».', max_length=16, verbose_name='Касса'),
        ),
    ]
