# Generated by Django 5.0.6 on 2026-10-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_sitesettings_kassa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='bonus_redeem_waiter',
            field=models.BooleanField(default=True, help_text='Официант или бариста находит гостя по телефону и списывает', verbose_name='Персонал списывает бонусы'),
        ),
    ]
